# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: 프로젝트 LIST
    submenu:
      - name: MyUtile
        link: /projects/MyUtile
      - name: OurLegacy
        link: /projects/ourlegacy
  - name: 게시물
    link: /
  - name: Tags
    link: /tags
  - name: 소개
    link: /about
  - name: Site & SNS
    submenu:
      - name: GitHub
        icon: github
        link: https://github.com/jkkim09
    
