# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: 프로젝트 LIST
    submenu:
      - name: MyUtils
        link: /projects/myutils
      - name: Quiz
        link: /projects/quiz
      - name: spring-boot&react
        link: /projects/springBootReact
      - name: vrTest
        link: /projects/vrTest
  - name: 게시물
    link: /
  - name: Tags
    link: /tags
  - name: 이전 소개
    link: /jkAbout
  - name: 소개
    link: /about
  - name: Site & SNS
    submenu:
      - name: GitHub
        icon: github
        link: https://github.com/jkkim09
    
